-- Credenciais administrativas nao sao armazenadas neste repositorio.
-- Depois de executar database/migrate.php, configure ADMIN_EMAIL e
-- ADMIN_PASSWORD no ambiente e execute database/criar-admin.php.
